services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    ports:
      - 9999:9999
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - app-1
      - app-2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  app-1:
    build: .
    container_name: app-1
    hostname: app-1
    environment:
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "80MB"

  app-2:
    build: .
    container_name: app-2
    hostname: app-2
    environment:
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "80MB"

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
